/*
 * Premium Select v0.1 Beta
 * 
 * @Author Jocko MacGregor
 * @Version 0.1b
 * 
 * A jQuery plugin for custom styling your select drop downs.
 * 
 * This code is based on the code presented in a tutorial by Martin Angelov
 * for tutorialzine.com.  To read the tutorial visit:
 * 
 * http://tutorialzine.com/2010/11/better-select-jquery-css3/
 */var console=console||{info:function(){}};$.fn.premiumSelect=function(){var e=$(this).filter("select");e.each(function(){$.premiumselect.init($(this))})};$.premiumselect={init:function(e){$.premiumselect.buildInterface(e)},buildInterface:function(e){var t,n=e.data("has-icon")===1,r=e.data("width");console.info(e.data("has-icon"));console.info(n);var i=e.data("theme"),s=$("<div>",{width:e.outerWidth(),id:(t=e.attr("id"))?t:null,className:"premiumSelect"+(i?" "+i:""),style:r?"min-width: "+r:null,html:'<div class="selectBox"></div>'}),o=$("<ul>",{className:"dropDown"}),u=s.find(".selectBox");e.find("option").each(function(t){var r=$(this);t===e.attr("selectedIndex")&&u.html(r.text());if(r.data("skip"))return!0;var i="",s,a=1,f,l;n&&(i+=(s=r.data("icon"))?'<img src="'+s+'" />':"");a=1;f=(l=r.data("line-"+a))?l:null;while(f){var c=n?" has-icon":"";i+='<span class="line-'+a+c+'">'+f+"</span>";a++;f=(l=r.data("line-"+a))?l:null}var h=r[0],p=e.find("option[data-skip!=1]")[0],d=e.find("option[data-skip!=1]:last")[0],v=h===p?"first":h===d?"last":null,m=$("<li>",{html:i,className:v});m.data("select",e);m.data("option",r);m.click(function(e){e.preventDefault();var t=$(this),n=$.premiumselect.getSelectBox(t),r=t.data("select"),i=t.data("option"),s=$.premiumselect.getDropDown(t);n.html(i.text());s.trigger("hide");r.val(i.val());return!1});o.append(m)});s.append(o.hide());e.hide().after(s);o.bind("show",function(){var e=$(this);if(e.is(":animated"))return!1;var t=$.premiumselect.getSelectBox(e);t.addClass("expanded");e.slideDown()}).bind("hide",function(){var e=$(this);if(e.is(":animated"))return!1;var t=$.premiumselect.getSelectBox(e);t.removeClass("expanded");e.slideUp()}).bind("toggle",function(){var e=$(this),t=$.premiumselect.getSelectBox(e);t.hasClass("expanded")?e.trigger("hide"):e.trigger("show")});u.click(function(){var e=$.premiumselect.getDropDown($(this));e.trigger("toggle");return!1});$(document).click(function(){$(".dropDown").trigger("hide")})},getSelectBox:function(e){return e.closest(".premiumSelect").find(".selectBox")},getDropDown:function(e){return e.closest(".premiumSelect").find(".dropDown")}};$(document).ready(function(){$("select.premiumSelect").premiumSelect()});